DROP TABLE IF EXISTS REGATTA;

CREATE TABLE REGATTA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    wedstrijd_naam VARCHAR(250) NOT NULL,
    name VARCHAR(250) NOT NULL,
    date DATE NOT NULL,
    max_teams INT NOT NULL,
    categorie VARCHAR(250) NOT NULL
)